((def zero 0.0)
 (def one 1.0)
 (def x one)
 (def n zero)
 (while0 n (block (def a zero)
                  (if0 a (block (def b 3.0)
                                (def a -1.0)
                                (x = (x + b)))
                         (x = a))
                  (n = (a + one))))
 x)