((def x 0.0)
 (def one 1.0)
 (def negOne -1.0)
 (def ten 10.0)
 (def result 0.0)
 (if0 x (block (x = (x + ten))
               (result = (result + one))
               (if0 x (x = (x + ten))
                      (block (def negFive -5.0)
                             (x = (x + negFive))
                             (x = (negFive + x))
                             (result = (result + ten))
                             (if0 x (block (x = (x + ten))
                                           (x = (x / negFive)))
                                    (x = 1.0)))))
        (x = -3.0))
 (result = (result + x))
 result)