((def ten 10.0)
 (def one 1.0)
 (def three 3.0)
 (def third (three / ten))
 (def pointOne (one / ten))
 (def pointTwo (pointOne + pointOne))
 (def pointThree (pointTwo + pointOne))
 (def a -1.0)
 (if0 (pointThree == third)
      (a = 1.0)
      (a = 0.0))
  a)
