(
    (tmodule ModuleA
        (class A (x) 
            (method getX () 
                (this --> x)
            )
            (method addX (y)
                (def z (this --> x))
                (this --> x = (z + y))
                (this --> x)
            )
        )
        (((x Number)) ((getX () Number) (addX (Number) Number)))
    )

    (tmodule ModuleB (import ModuleA)
        (class B () 
            (method makeA (x) 
                (new A (x))
            )
        )
        (() ((makeA (Number) (((x Number)) ((getX () Number) (addX (Number) Number))))))
    )
    (timport ModuleA (((x Number)) ((getX () Number) (addX (Number) Number))))
    (import ModuleB)
    (def w 1.0)
    (def y 2.0)
    (def x (new B ()))
    (def a (new A (y)))
    (a = (x --> makeA (w)))
    (a --> x)
)
