((module Data
  (class Data
    (value)
    (method get ()
      (def tmp (this --> value))
      tmp)
    (method bump (delta)
      (def old (this --> value))
      (def res (old + delta))
      (this --> value = res)
      res)))
 (module Extra
  (class Extra
    (factor)
    (method apply (arg)
      (def x arg)
      x)
    (method ignore (arg)
      (def y (this --> factor))
      y)))
 (tmodule
  TypedCalc
  (timport Data (((value Number))
                 ((get () Number) (bump (Number) Number))))
  (timport Extra (((factor Number))
                  ((apply (Number) Number) (ignore (Number) Number))))
  (class TypedCalc
    (store extra)
    (method init (start step)
      (def base start)
      (def inc step)
      (def data (new Data (base)))
      (def first (data --> bump (inc)))
      (def second (data --> bump (inc)))
      (def e (new Extra (inc)))
      (this --> store = second)
      (this --> extra = inc)
      second)
    (method compute (more)
      (def cur (this --> store))
      (def add more)
      (def res (cur + add))
      (this --> store = res)
      res)
    (method getstore ()
      (def s (this --> store))
      s))
  (((store Number) (extra Number))
   ((init (Number Number) Number)
    (compute (Number) Number)
    (getstore () Number))))
 (module Worker
  (import TypedCalc)
  (class Worker
    (calc backup)
    (method setup ()
      (def zero 0.0)
      (def step 3.0)
      (def init zero)
      (def t (new TypedCalc (zero zero)))
      (this --> calc = t)
      (this --> backup = t)
      0.0)
    (method run ()
      (def start 4.0)
      (def step 3.0)
      (def c (this --> calc))
      (def trash (c --> init (start step)))
      (def mid (c --> compute (step)))
      (def more 2.0)
      (def end (c --> compute (more)))
      (def keep (c --> getstore ()))
      (def ans (end + keep))
      ans)))
 (timport Worker (((calc Number) (backup Number))
                  ((setup () Number) (run () Number))))
 (def zero 0.0)
 (def w (new Worker (zero zero)))
 (def initres (w --> setup ()))
 (def r (w --> run ()))
 r)
