(
    (module ModuleA
        (class A (x) 
            (method getX () 
                (this --> x)
            )
            (method addX (y)
                (def z (this --> x))
                (this --> x = (z + y))
                (this --> x)
            )
        )
    )

    (module ModuleB (import ModuleA)
        (class A (x) 
            (method getX () 
                (this --> x)
            )
            (method addX (y)
                (def z (this --> x))
                (this --> x = (z + y))
                (this --> x)
            )
        )
    )
    (import ModuleB)
    (def w 1.0)
    (def x (new A (w)))
    x
)
