((module Foo (class foo (x) (method woo (nOne nTwo) (nOne + nTwo))))
(tmodule Bar (import Foo) (class foo (x y)) (((x Number) (y Number)) ()))
(import Bar)
(timport Foo (((x Number)) ((woo (Number Number) Number))))
(timport Foo (((x Number) (y Number)) ()))
(timport Foo (((x Number)) ((woo (Number Number) Number))))
(def one 1.0)
(def two 2.0)
(def three 3.0)
(def f (new foo (one)))
(g --> woo (two three)))
