((class Box (v)
   (method get () v)
   (method bump ()
     (def one 1.0)
     (v = (v + one))
     v))

 (class Holder (b)
   (method touch ()
     (def z 0.0)
     (b = (b + z))
     z))

 (class Driver ()
   (method run ()
     (def one 1.0)
     (def two 2.0)
     (def bx (new Box (one)))
     (def hd (new Holder (two)))
     (def k (bx --> bump()))
     (def m (hd --> touch()))
     (def s (k + m))
     s))

 (def one 1.0)
 (def two 2.0)
 (def drv (new Driver ()))
 (def bad (new Box one))
 (drv --> run()))
