((class Kit (x y)
   (method first () x)
   (method second () y)
   (method bumpx ()
     (def one 1.0)
     (x = (x + one))
     x)
   (method first ()
     (def z 0.0)
     (x = (x + z))
     x))

 (class Use (k)
   (method run ()
     (def a (k --> first()))
     (def b (k --> second()))
     (def s (a + b))
     s))

 (def one 1.0)
 (def two 2.0)
 (def k (new Kit (one two)))
 (def u (new Use (k)))
 (u --> run()))
