((class Accum (seed)
   (method add (a a b)
     (def s seed)
     (def t a)
     (def u b)
     (s = (s + t))
     (s = (s + u))
     s))

 (class Driver ()
   (method run ()
     (def one 1.0)
     (def two 2.0)
     (def three 3.0)
     (def ac (new Accum (one)))
     (def res (ac --> add (two three)))
     res))

 (def zz 0.0)
 (def d (new Driver ()))
 (d --> run ()))
