(
  (class Point (x y)
    (method set (dx dy)
      (def a (this --> x))
      (def b (this --> y))
      (this --> x = dx)
      (this --> y = dy)
      (a + b)
    )
    (method addX (v)
      (def old (this --> x))
      (this --> x = (old + v))
      (this --> x)
    )
  )
  (class Pair (first second)
    (method equalify ()
      (def x (this --> first))
      (def y (this --> second))
      (def t (x == y))
      t))

  (def nten 10.0)
  (def ntwenty 20.0)
  (def nthree 3.0)
  (def nfour 4.0)
  (def nfive 5.0)
  (def nsix 6.0)
  (def nzero 0.0)
  (def none 1.0)

  (def p (new Point (nten ntwenty)))
  (def q (new Point (nfive nthree)))
  (def r 0.0)
  (def flag 0.0)
  (def tmp 0.0)
  (def pair (new Pair (nfive nsix)))
  (def ax 0.0)
  (def bx 0.0)

  (r = (p --> set (nthree nfour)))
  (tmp = (q --> addX (nfive)))
  (p --> x = nten)
  (while0 flag
    (block
      (def inner 0.0)
      (flag = none)
      (tmp = (p --> set (nten ntwenty)))))
  (if0 (pair --> equalify ())
       (pair --> first = nzero)
       (pair --> second = none))
  (ax = (p --> x))
  (bx = (q --> x))

  (new Pair (ax bx))
)
