((module Set (class set () (method m (fancy) (fancy --> f = this) 777.0)))
 (tmodule Fancy (class fancy (f)) (((f Number)) ()))
 (timport Set (() ((m ((((f Number)) ())) Number))))
 (import Fancy)
 (def one 1.0)
 (def get (new fancy (one)))
 (def setter (new set ()))
 (def yyy (setter --> m (get)))
 1.0)
