((module Test (class Test (x) (method getX () (this --> x))))
(module Mutator (class Mutator (test) (method mutate () (def y (this --> test)) (y --> x = 2.0) 0.0)))
    (import Test)
    (import Mutator)
    (def x 1.0)
    (def test (new Test (x)))
    (def mutator (new Mutator (test)))
    (x = (mutator --> mutate ()))
    (test --> getX ()))