package ast

object ExprRenamer:

    // Private iterator that will produce fresh names
    // The counter is monotonically increasing + surface syntax does not allow 
    // numbers in names => all the names generated by this method will be globally
    // unique.
    private val nameAnnotGenerator = Iterator.from(0)
    private def uniquifyName(x: String) : String = x + nameAnnotGenerator.next().toString()

    def unqiuifyVarNames(vars : Set[String]) : Map[String, String] = 
        vars.map(originalName => (originalName, uniquifyName(originalName))).toMap

    def getAllVars(e : CleanExpr) : Set[String] = e match
        case Expr.Num(_, _) => Set()
            
        case Expr.Var(x, _) => Set(x)
            
        case Expr.BinOpExpr(lhs, _, rhs, _) => Set(lhs, rhs) 
            
        case Expr.NewInstance(_, args, _) => args.toSet

        case Expr.GetField(instance, _, _) => Set(instance)
            
        case Expr.CallMethod(instance, _, args, _) => args.toSet.incl(instance)
            
        case Expr.IsInstanceOf(instance, _, _) => Set(instance)

    def renameVars(e : CleanExpr, renameMap : Map[String, String]) : CleanExpr = e match
        case Expr.Num(n, range) => Expr.Num(n, range)
            
        case Expr.Var(x, range) => Expr.Var(renameMap(x), range)
            
        case Expr.BinOpExpr(lhs, op, rhs, range) =>
            Expr.BinOpExpr(renameMap(lhs), op, renameMap(rhs), range)
            
        case Expr.NewInstance(cname, args, range) =>
            Expr.NewInstance(cname, args.map(renameMap(_)), range)

        case Expr.GetField(instance, field, range) =>
            Expr.GetField(renameMap(instance), field, range)
            
        case Expr.CallMethod(instance, method, args, range) =>
            Expr.CallMethod(renameMap(instance), method, args.map(renameMap(_)), range)
            
        case Expr.IsInstanceOf(instance, cname, range) =>
            Expr.IsInstanceOf(renameMap(instance), cname, range)
