(
  (module N (class C () (method id () 222.0)))
  (module M (import N)
    (class C ()
      (method id () 111.0)
      (method run ()
        (def t (new C ()))
        (t --> id ())
      )
    )
  )
  (import M)
  (def o (new C ()))
  (o --> run ())
)
