(
  (module M (class C () (method val () 17.0)))
  (module N 
    (class C ()
      (method val () 39.0)
      (method go ()
        (def x (new C ()))
        (x --> val ())
      )
    )
  )
  (import M)
  (def y (new C ()))
  (y --> go ())
)
