(
  (module M 
    (class C ()
      (method val () 49.0)
      (method go ()
        (def x (new C ()))
        (x --> val ())
      )
    )
  )
  (module M 
    (import M)
    (class C ()
      (method val () 39.0)
      (method go ()
        (def x (new C ()))
        (x --> val ())
      )
    )
  )
  (import M)
  (def y (new C ()))
  (y --> go ())
)
