((class MyClass
        (fieldA fieldB fieldC)
        (method myMethod
                (paramA paramB)
                (def a paramA)
                (if0 a (a = -1.0)
                       (block (def b paramB)
                              (a = (a + b))
                       )
                )
                a
        )
 )
 (class MyClass
         ()
 )
 (def fA 0.0)
 (def fB 1.0)
 (def fC 2.0)
 (def a (new MyClass (fA fB fC)))
 (fA = (a --> fieldB))
 (fB = (a --> fieldA))
 (a --> fieldC = 5.0)
 (a --> myMethod (fA fB))
)