(
    (class A (x y z)
             (method addition (a b)
                              (def c (new B ()))
                              (def d c)
                              (b = (a + b))
                              (b = a)
                              (c = b)
                              b
             )
    )
    (class B (x y)
             (method cbm () (new A ())))

    (class C (x)
             (method test (a b c)
                          (a --> fieldX = (new D (b c)))
                          (b = (a --> fieldX))
                          (b --> test (c)))
             (method otherTest (a b)
                               (def newClass (new D (a b)))
                               (this --> test (newClass a b))))
    (class D (x y)
             (method test (a b c)
                          (def result 0.0)
                          (def x (this --> x))
                          (def y (this --> y))
                          (a --> fieldX = (new C (b c)))
                          (b = (a --> fieldX))
                          (c = (this --> otherTest (a b)))
                          (if0 (a --> test (result b c))
                               (if0 (b isa C)
                                    (result = (b --> test (c)))
                                    (result = (c isa D)))
                               (while0 (a --> test (x y result))
                                       (block (def one 1.0)
                                              (def two 2.0)
                                              (def newB (new B (one two)))
                                              (if0 (newB --> cbm ())
                                                   (result = (newB --> x))
                                                   (result = (this --> otherTest (one two)))))))
                          (b --> test (c)))
             (method otherTest (a b)
                               (def newClass (new C (a b)))
                               (this --> test (newClass a b))))


    (def objectA (new A ()))
    (def one 1.0)
    (def two 2.0)
    (def result (objectA --> addition (one two)))
    (result isa A)
)