((def result 0.0)
 (def zero 0.0)
 (def one 1.0)
 (def two (one + one))
 (def x zero)
 (def y 10.)
 (def twenty -1.0)
 (while0 x
        (block (def ten 10.0)
               (if0 (y == zero)
                    (x = one)
                    (block (def negOne -1.0)
                           (y = (y + negOne))
                           (result = (result + ten))))))
 (twenty = 20.0)
 (if0 (result == twenty)
      (result = (result + twenty))
      (block (def minusFifty -50.0)
             (result = (result + minusFifty))))
 result)