((def a 0.0)
 (def b 10.0)
 (def c -1.0)
 (def three 3.0)
 (while0 a
         (block (def e 3.0)
                (if0 (b == three)
                     (a = 1.0)
                     (block (def d 8.0)
                            (b = (b + c))
                            (b = (b / e))
                     )
                )
         )
 )
 a
)
