((class Car (w s))
(class Wheel (year diameter))
(class Seat (width))
(def sixtyEight 68.0)
(def twenty 20.0)
(def smallWheel (new Wheel (twenty sixtyEight)))
(def alsoSmallWheel (new Wheel (twenty sixtyEight)))
(def seat (new Seat (sixtyEight)))
(def carOne (new Car (smallWheel seat)))
(def carTwo (new Car (alsoSmallWheel seat)))
(carOne == carTwo)
)