((class vec (x y)
   (method sum ()
     (def a (this --> x))
     (def b (this --> y))
     (a + b)))
 (class acc (val)
   (method addfromvec (vec inc)
     (def s (vec --> sum ()))
     (def base (this --> val))
     (if0 inc
          (block (this --> val = (base + s)))
          (block (this --> val = base)))
     (while0 inc
       (block
         (this --> val = (this --> val))
         (inc = 1.0)))
     (this --> val)))
 (def zero 0.0)
 (def one 1.0)
 (def vx 5.0)
 (def vy 6.0)
 (def acczero 0.0)
 (def v (new vec (vx vy)))
 (def a (new acc (acczero)))
 (a --> val = (a --> addfromvec (v zero)))
 (a --> val))
