((class foo (a b)
   (method mix (t u)
     (def x (this --> a))
     (def y (this --> b))
     (def sum (x + y))
     (if0 t
          (block (this --> a = (sum + u)))
          (block (this --> b = (sum + u))))
     (while0 t (block (t = u)))
     (this --> a)))
 (class bar (f)
   (method combine (p tt uu)
     (def tmp (p --> mix (tt uu)))
     (def pa (p --> a))
     (def fv (this --> f))
     (pa + fv)))
 (def zero 0.0)
 (def one 1.0)
 (def two 2.0)
 (def three 3.0)
 (def four 4.0)
 (def five 5.0)
 (def p (new foo (two three)))
 (def b (new bar (five)))
 (b --> combine (p zero four)))
