((class p (x y)
   (method sumaftermut (z)
     (def ylocal (this --> y))
     (def xlocal z)
     (this --> y = xlocal)
     (xlocal = 1.0)
     (if0 z
          (block (this --> x = ylocal))
          (block (this --> x = xlocal)))
     (while0 z (block (z = 1.0)))
     (xlocal + ylocal)))
 (def zzero 0.0)
 (def x 10.0)
 (def y 7.0)
 (def pt (new p (x y)))
 (def res (pt --> sumaftermut (zzero)))
 (def sx (pt --> x))
 (res + sx))

