((class Box (x)
    (method swapAdd (y)
      (def tmp (this --> x))
      (this --> x = y)
      (tmp + y)))
  (def x 2.0)
  (def box (new Box (x)))
  (def twin box)
  (def inc 3.0)
  (def s (box --> swapAdd (inc)))
  (def out (twin --> x))
  (def ok (out == inc))
  (if0 ok
      (block (s = (s + out)))
      (block (s = 999.0)))
  s)
