((module A (class A ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 (timport A (() ()))
 0.0)