((module A (class A ()))
 (module Another (class A ()))
 (module B (import A) (class B ()))
 (tmodule Banother (class B ()) (() ()))
 (tmodule C
    (timport A (() ()))
    (timport Another (() ()))
    (timport B (() ()))
    (import Banother)
    (class C ()))
 (import C)
 (timport Another (() ()))
 (timport A (() ()))
 (timport B (() ()))
 0.0)