((module A (class A ()))
 (module B (import A) (class B ()))
 (module C (import B) (class C ()))
 (module D (import C) (class D ()))
 (module E (import D) (class E ()))
 (module F (import E) (class F ()))
 (module G (import F) (class G ()))
 (module H (import G) (class H ()))
 (module I (import H) (class I ()))
 (module J (import I) (class J ()))
 (tmodule T (timport J (() ())) (class T ()) (() ()))
 (timport J (() ()))
 0.0)