(
    (module untypedA (class c (x)))
    (tmodule typedA
             (timport untypedA (() ()))
             (class c (x)
                      (method return () (this --> x)))
             (((x Number)) ((return () Number)))
    )
    (tmodule typedB
             (import typedA)
             (timport untypedA (((x Number)) ()))
             (class add (x)
                        (method adding
                                (a b)
                                (def x 1.0)
                                (def this (new c (x)))
                                (def sum (this --> x))
                                (sum = (a + b))
                                sum)
             )
             (((x Number)) ((adding (Number Number) Number)))
    )
    (import typedB)
    (timport untypedA (((x Number)) ()))
    (def one 1.0)
    (def two 2.0)
    (def a (new add (one)))
    (def b (new c (two)))
    (def c (a --> adding (one one)))
    c
)