((tmodule Vehicle
    (class Car (year tankAmount)
      (method getYear ()
        (this --> year)))
    (((year Number)
      (tankAmount Number))
     ((getYear () Number))))
  (tmodule SeaVehicle
    (import Vehicle)       
    (class boat (length tankAmount)
      (method getLength ()
        (this --> length)))
    (((length Number)
      (tankAmount Number))
     ((getLength () Number))))
  (import SeaVehicle)
  (def nine -9.0)
  (def ten 10.0)
  (new boat (nine ten)))