(
    (class A ()
        (method f (x y)
            (def y 0.0)
            (def z (new B (x)))
            (while0 y
                (block
                    (def znew (new B (x)))
                    (z --> a = znew)
                    (znew --> b = y)
                    (x = (znew + x))
                    (z = a)
                )
            )
            (z + x)
        )
    )
    (class B (n))
    (def a 0.0)
    (def b 0.0)
    (def c 1.0)
    (a = (b --> n))
    (a = (new A (a b)))
    (a = (a --> f (b c)))
    (while0 0.0
        (block
            (def x a)
            (a = (x + c))
            (x = (new B (a)))
        )
    )
    (c --> f (a))
)