(
  (module A (class A ()))
  (module B (class B ()))
  (module C (class C ()))
  (module D (import B) (class D ()))
  (tmodule E (timport D (() ())) (class E ()) (() ()))
  (tmodule F (timport D (() ())) (timport D (() ())) (timport D (() ())) (class F ()) (() ()))
  (module G (import E) (import F) (class G ()))
  (timport D (() ()))
  (timport D (() ()))
  (timport D (() ()))
  (import E)
  (import E)
  (import F)
  (import E)
  (import F)
  (timport B (() ()))
  (timport G (() ()))
  (timport B (() ()))
  1.0
)