(
  (class Factory (initialValue)
    (method create ()
      (def val (this --> initialValue))
      (new Counter (val))
    )
  )
  (class Counter (count)
    (method get ()
      (this --> count))
  )
  (def zero 0.0)
  (def f (new Factory (zero)))
  (f --> create ())
)