(
  (class Counter (val)
    (method getValue ()
      (this --> val)
    )
    (method doubleValue ()
      (def a 0.0)
      (def b 0.0)
      (a = (this --> getValue ()))
      (b = (this --> getValue ()))
      (a + b)
    )
  )
  (def seven 7.0)
  (def c (new Counter (seven)))
  (c --> doubleValue ())
)
