((tmodule module (class module (module)
                (method module (o) (o isa module)))
    (((module Number)) ((m (Number) Number))))

(import module)
(def module 1.0)
(def b 2.0)
(def x (new module (module b)))
(def y (x --> module (module)))
(y == x))