package ast

object ExprRenamer:

    // Private iterator that will produce fresh names
    // The counter is monotonically increasing + surface syntax does not allow 
    // numbers in names => all the names generated by this method will be globally
    // unique.
    private val nameAnnotGenerator = Iterator.from(0)
    private def uniquifyName(x: String) : String = x + nameAnnotGenerator.next().toString()

    def unqiuifyVarNames(vars : Set[String]) : Map[String, String] = 
        vars.map(originalName => (originalName, uniquifyName(originalName))).toMap

    def getAllVars(e : CleanExpr) : Set[String] = e match
        case Expr.Num(n) => Set()
            
        case Expr.Var(VarRef(x)) => Set(x)
            
        case Expr.BinOpExpr(VarRef(lhs), op, VarRef(rhs)) => Set(lhs, rhs) 
            
        case Expr.NewInstance(cname, args) => 
            args.map(arg => arg.x).toSet

        case Expr.GetField(VarRef(instance), field) => 
            Set(instance)
            
        case Expr.CallMethod(VarRef(instance), method, args) => 
            args.map(arg => arg.x).toSet.incl(instance)
            
        case Expr.IsInstanceOf(VarRef(instance), cname) => 
            Set(instance)

    def renameVars(e : CleanExpr, renameMap : Map[String, String]) : CleanExpr = e match
        case Expr.Num(n) => Expr.Num(n)
            
        case Expr.Var(VarRef(x)) => 
            Expr.Var(VarRef(renameMap(x)))
            
        case Expr.BinOpExpr(VarRef(lhs), op, VarRef(rhs)) => 
            Expr.BinOpExpr(VarRef(renameMap(lhs)), op, VarRef(renameMap(rhs)))
            
        case Expr.NewInstance(cname, args) => 
            Expr.NewInstance(cname, args.map(arg => VarRef(renameMap(arg.x))))

        case Expr.GetField(VarRef(instance), field) => 
            Expr.GetField(VarRef(renameMap(instance)), field)
            
        case Expr.CallMethod(VarRef(instance), method, args) => 
            Expr.CallMethod(VarRef(renameMap(instance)), method, args.map(arg => VarRef(renameMap(arg.x))))
            
        case Expr.IsInstanceOf(VarRef(instance), cname) => 
            Expr.IsInstanceOf(VarRef(renameMap(instance)), cname)
