((tmodule TMod
          (class TClass
            (f g)
            (method m (h)
                    (def G (this --> g))
                    (def F (this --> f))
                    (def FplusG (F + G))
                    (FplusG + h)))
          (((f Number) (g Number)) ((m (Number) Number))))
 (import TMod)
 (def F 1.0)
 (def G 2.0)
 (def t (new TClass (F G)))
 (def H 7.0)
 (t --> g = 3.0)
 (t --> m (H)))