((module ModA
   (class Counter ()
     (method add (x)
       (def one 1.0)
       (x + one))
     (method makeCounter ()
       (new Counter ()))))
 (module ModB
   (import ModA)
   (class Counter ()
     (method add (x)
       (def two 2.0)
       (x + two))
     (method makeCounter ()
       (new Counter ()))))
 (import ModA)
 (import ModB)
 (def factory (new Counter ()))
 (def newCounter (factory --> makeCounter ()))
 (def zero 0.0)
 (newCounter --> add (zero)))