((module ModA (class Point (x y)))
 (module ModB
   (class Mutator ()
     (method changeX (obj newVal)
       (obj --> x = newVal)
       newVal)))
 (import ModA)
 (import ModB)
 (def five 5.0)
 (def ten 10.0)
 (def res 0.0)
 (def p (new Point (five ten)))
 (def m (new Mutator ()))
 (def twenty 20.0)
 (res = (m --> changeX (p twenty)))
 (p --> x))