((module ModCounter
   (class Counter (value)
     (method get () (this --> value))
     (method inc ()
       (def v (this --> get ()))
       (def one 1.0)
       (def zero 0.0)
       (if0 zero
            (block
              (def newVal (v + one))
              (this --> value = newVal))
            (v = 4.0))
       (this --> get ()))))
 (import ModCounter)
 (def inter 0.0)
 (def zero 0.0)
 (def c (new Counter (zero)))
 (inter = (c --> inc ()))
 (inter = (c --> inc ()))
 (c --> get ()))