((module ModNode (class Node (next)))
 (import ModNode)
 (def zero 0.0)
 (def a (new Node (zero)))
 (def b (new Node (zero)))
 (def result 0.0)
 (a --> next = a)
 (b --> next = b)
 (if0 (a == b)
      (result = 1.0)
      (result = 2.0))
 result)