((module blank (class blank () (method nothing () 0.0)))
(module blank (class Point (x y) (method delta (x) (def y (this --> y)) (x = 1.0) (x + y))))
    (tmodule
  Point (timport blank (() ((nothing () Number))))
  (class Point (x y) (method delta (x) (def y (this --> y)) (x = 1.0) (x + y)))
  (((x Number) (y Number)) ((delta (Number) Number))))
 (import Point)
 (timport blank (() ((nothing () Number))))
 (def x 1.0)
 (def point (new Point (x x)))
 (point --> x = x)
 (x = (point --> delta (x)))
 x)
