((tmodule Foo (class foo (x) (method woo (nOne nTwo) (nOne + nTwo))) (((x Number)) ((woo (Number Number) Number))))
(tmodule Bar (import Foo) (class foo (x y)) (((x Number) (y Number)) ()))
(import Bar)
(import Foo)
(def one 1.0)
(def two 2.0)
(def three 3.0)
(def f (new foo (one)))
f)
