((module K (class A () (method v () 50.0)))
(module L (class A () (method v () 60.0)))
(module M (import K) (import L)
(class A ()
(method v () 5.0)
(method pick () (def t (new A ())) (t --> v ()))))
(import M)
(def o (new A ()))
(o --> pick ()))