((module U (class U () (method u () 1.0)))
(module T (import U) (class T () (method makeU () (def a (new U ())) 0.0)))
(module S (import T)
(class S ()
(method go ()
(def x 1.0)
(def y 2.0)
(def o (new U ()))
(x = (x + y))
x)))
(import S)
(def s (new S ()))
(s --> go ()))