((tmodule A (class A ()) (() ()))
 (module B (import A) (class B ()))
 (tmodule C (import A) (timport B (() ())) (class C ()) (() ()))
 (tmodule D (import A) (timport B (() ())) (import C) (class D ()) (() ()))
 (module E (import A) (import B) (import C) (import D) (class E ()))
 (module F (import A) (import B) (import C) (import D) (import E) (class F ()))
 (tmodule G (import A) (timport B (() ())) (import C) (import D) (timport E (() ())) (timport F (() ())) (class G ()) (() ()))
 (module H (import A) (import B) (import C) (import D) (import E) (import F) (import G) (class H ()))
 (tmodule I (import A) (timport B (() ())) (import C) (import D) (timport E (() ())) (timport F (() ())) (import G) (timport H (() ())) (class I ()) (() ()))
 (module J (import A) (import B) (import C) (import D) (import E) (import F) (import G) (import H) (import I) (class J ()))
 (tmodule T (import A) (timport B (() ())) (import C) (import D) (timport E (() ())) (timport F (() ())) (import G) (timport H (() ())) (import I) (timport J (() ())) (class T ()) (() ()))
 (import A) (timport B (() ())) (import C) (import D) (timport E (() ())) (timport F (() ())) (import G) (timport H (() ())) (import I) (timport J (() ()))
 0.0)