((def x -999.9)
 (def y 1000.0)
 (while0 (x == y) 
         (block (x = (x + step))
                (if0 (x / two)
                     (inner = (x == y))
                     (block (inner = (x == zero))
                            (inner = (inner + y))))))
 (def result (x / y))
 result)