((tmodule module (class C () (method mtwo (this) this)) ( ()
                                      ( (mtwo  (Number) Number)  )
                                                                   ))
          (import module)
                     (def ten 10.0)
                                ten)