((tmodule mod (class A ()) (() ()))
         (tmodule module (import mod)
           (class C () (method mtwo (x y z) (new A ())))
           (() ((mtwo (Number Number Number) (() ())))))
         (import module)
         (def ten 10.0)
         (def c (new C ()))
         (ten = (c --> mtwo (ten ten ten)))
         ten)