((tmodule mod (class A ()) (() ()))
              (tmodule module (import mod)
                (class C (a))
                (((a (() ()))) ()))
              (import module)
              (import mod)
              (def ten 10.0)
              (def a (new A ()))
              (def c (new C (a)))
              (a = (c --> a))
              ten)