(
    (class Square (posn length)
        (method xLocation ()
            (def p (this --> posn))
            (p --> x)
        )
        (method yLocation ()
            (def p (this --> posn))
            (p --> y)
        )
    )
    (class posn (x y)
        (method add ()
            (def x (this --> x))
            (def y (this --> y))
            (x + y)
        )
        (method makeSquare (length)
            (new Square (this length))
        )
    )
    (def a 1.0)
    (def point (new posn (a a)))
    (def result (point --> makeSquare(a)))

    (result --> xLocation ())
)