((module A (class c ()))
 (module B (class c () (method m () 2.0)))
 (import A)
 (import B)
 (import A)
 (import B)
 (import A)
 (import B)
 (import A)
 (import B)
 (def ex (new c ()))
 (def res (ex --> m ()))
 res)
