(
  (zero = 0.0)
  (one = 1.0)
  (mone = -1.0)
  (two = 2.0)
  (three = 3.0)
  (four = 4.0)
  (five = 5.0)
  (ten = 10.0)
  (hundred = 100.0)
  (failures = 520.0)

  (tee = 0.0)
  (you = 0.0)
  (vee = 0.0)
  (doubleyou = 0.0)
  (temp = 0.0)
  (expect = 0.0)
  (flag = 0.0)

  (ex = 42.0)
  (why = 42.0)
  (cmp = (ex == why))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (why = 41.0)
  (cmp = (ex == why))
  (if0 cmp (block (failures = (failures + one))) (block (tee = tee)))

  (kay = 0.0)
  (if0 kay (block (kay = 7.0)) (block (kay = 99.0)))
  (expect = 7.0)
  (cmp = (kay == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (kay = 1.0)
  (if0 kay (block (kay = 7.0)) (block (kay = 99.0)))
  (expect = 99.0)
  (cmp = (kay == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (count = 0.0)
  (flag = 0.0)
  (while0 flag
    (block
      (count = (count + one))
      (flag = 1.0)
    )
  )
  (expect = 1.0)
  (cmp = (count == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (eye = 0.0)
  (goal = 10.0)
  (flag = 0.0)
  (while0 flag
    (block
      (eye = (eye + one))
      (cmp = (eye == goal))
      (if0 cmp (block (flag = 1.0)) (block (flag = 0.0)))
    )
  )
  (cmp = (eye == goal))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (outer = 0.0)
  (sum = 0.0)
  (goal = 10.0)
  (flag = 0.0)
  (while0 flag
    (block
      (sum = (sum + one))
      (outer = (outer + one))
      (cmp = (outer == goal))
      (if0 cmp (block (flag = 1.0)) (block (flag = 0.0)))
    )
  )
  (expect = 10.0)
  (cmp = (outer == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))
  (expect = 10.0)
  (cmp = (sum == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (pee = 1.0)
  (cue = -1.0)
  (are = (pee + cue))
  (shots = 0.0)
  (while0 are
    (block
      (shots = (shots + one))
      (pee = (pee + one))
      (are = (pee + cue))
    )
  )
  (expect = 1.0)
  (cmp = (shots == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (neg = -123.0)
  (negtwo = -123.0)
  (cmp = (neg == negtwo))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (num = 100.0)
  (den = 5.0)
  (iszero = (den == zero))
  (if0 iszero (block (quot = quot)) (block (quot = (num / den))))
  (expect = 20.0)
  (cmp = (quot == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (dentwo = 2.0)
  (iszero = (dentwo == zero))
  (if0 iszero (block (quot = quot)) (block (quot = (quot / dentwo))))
  (if0 iszero (block (quot = quot)) (block (quot = (quot / dentwo))))
  (expect = 5.0)
  (cmp = (quot == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ay = 10.0)
  (ay = (ay + one))
  (ay = (ay + mone))
  (expect = 10.0)
  (cmp = (ay == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (bee = 0.0)
  (see = 300.0)
  (flag = 0.0)
  (while0 flag
    (block
      (bee = (bee + one))
      (see = (see + mone))
      (cmp = (see == zero))
      (if0 cmp (block (flag = 1.0)) (block (flag = 0.0)))
    )
  )
  (expect = 300.0)
  (cmp = (bee == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))
  (cmp = (see == zero))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ell = 12.0)
  (arr = 12.0)
  (eq = (ell == arr))
  (if0 eq (block (doubleyou = 777.0)) (block (doubleyou = 888.0)))
  (expect = 777.0)
  (cmp = (doubleyou == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ell = 9.0)
  (arr = 8.0)
  (eq = (ell == arr))
  (if0 eq (block (doubleyou = 111.0)) (block (doubleyou = 222.0)))
  (expect = 222.0)
  (cmp = (doubleyou == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ticks = 0.0)
  (flag = 0.0)
  (while0 flag
    (block
      (ticks = (ticks + one))
      (flag = 1.0)
    )
  )
  (expect = 1.0)
  (cmp = (ticks == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (dee = 25.0)
  (steps = 0.0)
  (flag = 0.0)
  (while0 flag
    (block
      (dee = (dee + mone))
      (steps = (steps + one))
      (cmp = (dee == zero))
      (if0 cmp (block (flag = 1.0)) (block (flag = 0.0)))
    )
  )
  (expect = 0.0)
  (cmp = (dee == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))
  (expect = 25.0)
  (cmp = (steps == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (num = 123.0)
  (den = 0.0)
  (keep = num)
  (iszero = (den == zero))
  (if0 iszero (block (num = num)) (block (num = (num / den))))
  (cmp = (num == keep))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ay = 3.0)
  (bee = 3.0)
  (seeletter = 3.0)
  (cmp = (ay == bee))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))
  (cmp = (bee == seeletter))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))
  (cmp = (ay == seeletter))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (ex = 7.0)
  (why = 5.0)
  (ztwo = (ex + why))
  (cue = 3.0)
  (rtwo = (ztwo / cue))
  (expect = 4.0)
  (cmp = (rtwo == expect))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  (eye = 0.0)
  (goal = 200.0)
  (flag = 0.0)
  (while0 flag
    (block
      (eye = (eye + one))
      (cmp = (eye == goal))
      (if0 cmp (block (flag = 1.0)) (block (flag = 0.0)))
    )
  )
  (cmp = (eye == goal))
  (if0 cmp (block (tee = tee)) (block (failures = (failures + one))))

  failures
)
