((x = -500.2)
 (y = 750.7)
 (if0 (x == y)
      (z = (x / if0))
      (block (temp1 = (x / y))
             (temp2 = (y + temp1))
             (if0 (temp2 == zero)
                  (while0 (temp1 == temp2)
                          (temp2 = (temp2 + x)))
                  (while0 (temp1 == temp2)
                          (temp2 = (temp2 + x))))))
 (z == result))