((x = -500.2)
 (y = 750.7)
 (if0 (x == y)
      (z = (x / if0))
      (block (temp = (x / y))
             (tempp = (y + temp))
             (if0 (temp2 == zero)
                  (while0 (temp == tempp)
                          (tempp = (tempp + x)))
                  (while0 (temp == tempp)
                          (tempp = (tempp + x))))))
 (z == result))