((module
   Flexible
   (class Flexible (x y)
     (method getX () (this --> x))
     (method getY () (this --> y))
     (method sum ()
       (def xVal (this --> x))
       (def yVal (this --> y))
       (xVal + yVal))))
 (tmodule
   UseAsPoint
   (timport Flexible (((x Number) (y Number)) ((getX () Number) (getY () Number) (sum () Number))))
   (class UseAsPoint (f)
     (method useBoth ()
       (def temp (this --> f))
       (def s (temp --> sum ()))
       (def x (temp --> getX ()))
       (s + x)))
   (((f (((x Number) (y Number)) ((getX () Number) (getY () Number) (sum () Number)))))
    ((useBoth () Number))))
 (import UseAsPoint)
 (timport Flexible (((x Number) (y Number)) ((getX () Number) (getY () Number) (sum () Number))))
 (def one 1.0)
 (def two 2.0)
 (def f (new Flexible (one two)))
 (def uap (new UseAsPoint (f)))
 (uap --> useBoth ()))