(
    (module K (class C ()))
    (module L (import L) 
        (class D (x) 
            (method dmaker (x) (new D (x)))))
    (import L)
    (import K)
    (def c (new C()))
    (def num 413.0)
    (def d (new D(c)))
    (def dd (d --> dmaker(num)))
    (dd --> x)
)