((module A (class c ()))
 (tmodule B (class c () (method m () 2.0)) (() ((m () Number))))
 (timport A (() ()))
 (import B)
 (timport A (() ()))
 (import B)
 (timport A (() ()))
 (import B)
 (timport A (() ()))
 (import B)
 (def ex (new c ()))
 (def res (ex --> m ()))
 res)
