((module A (class c ()))
 (module B (class c ()))
 (timport A (() ()))
 (timport B (() ()))
 (timport A (() ()))
 (timport B (() ()))
 (timport A (() ()))
 (timport B (() ()))
 (timport A (() ()))
 (timport B (() ()))
 (def res (new c ()))
 1.0)
