((tmodule M
   (class P (x y)
     (method sum ()
       (def tx (this --> x))
       (def ty (this --> y))
       (tx + ty)))
   (((x Number) (y Number)) ((sum () Number))))
 (import M)
 (def a 2.0)
 (def b 4.0)
 (def p (new P (a b)))
 (p --> sum ()))