((tmodule M
   (class Box (x)
     (method inc ()
       (def t (this --> x))
       (this --> x = (t + t))
       (this --> x)))
   (((x Number)) ((inc () Number))))
 (import M)
 (def one 1.5)
 (def b (new Box (one)))
 (b --> inc ()))