((module X (class X (x)))
 (tmodule Y
    (timport X (((x Number)) ()))
    (timport X (((x Number)) ()))
    (class Y (x))
    (((x Number)) ()))
 (tmodule N
    (class D ()
        (method Add (x y) (x + y)))
        (() ((Add (Number Number) Number))))
 (module O
    (class E ()
        (method Subtract (x y) (def negOne -1.0)
                               (def negY (y / negOne))
                               (x + negY))))
 (module M
    (import O)
    (import N)
    (class F ()
        (method Math () (def adder (new D ()))
                        (def subtracter (new E ()))
                        (def result 0.0)
                        (def four 4.0)
                        (def three 3.0)
                        (result = (adder --> Add (three four)))
                        (result = (adder --> Add (result three)))
                        (result = (subtracter --> Subtract (result four)))
                        result
        )
    )
 )
 (timport M (() ((Math () Number))))
 (timport X (((x (() ()))) ()))
 (import Y)
 (def f (new F ()))
 (f --> Math ())
)