((tmodule
  Point
  (class Point (x y) 
    (method delta (x) (def y (this --> y)) (x = 1.0) (x + y)))
  (((x Number) (y Number)) ((delta (Number) Number))))
  (tmodule 
  VectorUtils
  (class VectorUtils ()
    (method pointSum (a b)
      (def aX (a --> x)) 
      (def aY (a --> y))
      (def bX (b --> x))
      (def bY (b --> y))
      (def tmpX (aX + bX))
      (def tmpY (aY + bY))
      (tmpX + tmpY)
    )
  )
  (() ((pointSum ((((x Number) (y Number)) ((delta (Number) Number))) (((x Number) (y Number)) ((delta (Number) Number)))) Number)))
  )
 (import VectorUtils)
 (import Point)
 (def x 1.0)
 (def y 2.0)
 (def pointOne (new Point (y x)))
 (def pointTwo (new Point (x y)))
 (def vectUtils (new VectorUtils ()))
 (vectUtils --> pointSum (pointOne pointTwo)))
