((class Person (name age)
    (method getName () name)
    (method olderThan (other)
      (def t 1.0)
      (this --> name = 11.0)
      (if0 (other == other)
        (block
          (t = 2.0))
        (block
          (t = 1.0)))
      t
    )
  )
  (class Box (val)
    (method id (x)
      (def z 1.0)
      (z = x)
      z
    )
  )
  (def a 1.0)
  (def b 2.0)
  (def c 3.0)
  (def obj (new Box (a)))
  (def pOne (new Person (a b)))
  (def temp (obj --> val))
  (def nm (pOne --> getName ()))
  (a = (a + b))
  (temp = (obj --> id (a)))
  (while0 (a == b)
    (a = b))
  (if0 (a == c)
    (block
      (def k 1.0)
      (a = (a / k)))
    (block
      (def m 1.0)
      (b = (b + m))))
  (obj --> val = b)
  (pOne isa Person)
)