((class Point (x y)
     (method move (dx dy)
       (def newX (this --> x))
       (def newY (this --> y))
       (newX = (newX + dx))
       (newY = (newY + dy))
        (this --> x = newX)
        (this --> y = newY)
       (this --> y)))

(class Point (y z)
      (method a (y)
      (y = (y + y))
      y))

    (def startx 0.0)
    (def starty 0.0)
    (def endx 1.0)
    (def endy 1.0)
    (def result 0.0)
  (def p (new Point (startx starty)))
  (result = (p --> move (endx endy)))
  (p --> y))