((class Point (x y)
    (method move (dx dy)
      dx)
    (method move (dxa dya)
            dx))

    (def startx 0.0)
    (def starty 0.0)
    (def endx 1.0)
    (def endy 1.0)
    (def result 0.0)
  (def p (new Point (startx starty)))
  (result = (p --> move (endx endy)))
  (p --> y))