((class Point (x y)
    (method move (dx dy)
      (def newX x)
      (def newY y)
      (newX = (newX + dx))
      (newY = (newY + dy))
       (x = newX)
       (y = newY)
      y))

    (def startx 0.0)
    (def starty 0.0)
    (def endx 1.0)
    (def endy 1.0)
    (def result 0.0)
  (def p (new Point (startx starty)))
  (result = (p --> move (endx endy)))
  (p --> y))