((module X (class B () (method m (o) 2.0)))

(tmodule M (timport X (() ((m (Number) Number))))
           (timport X (() ((m (Number Number) Number))))
                (class A ()
                 (method m (o) (o isa B)))
    (() ((m ((() ((m (Number) Number)))) Number))))

(import M)
(timport X (() ((m (Number) Number))))
(def b (new B ()))
(def x (new A ()))
(def y 2.0)
(def r 1.0)
(r = (x --> m (b)))
r)