((module A
    (class C (fA fB fC)
        (method m (pQ pR)
            (this --> fA = pQ)
            (this --> fB = pR)
            (this --> fC = (pQ == pR))
            this
        )
    )
 )
 (module B (import A)
    (class D (fD fE)
        (method m (pQ pR pS)
            (def newC (new C (pQ pR pS)))
            (def a (newC --> fA))
            (def b (newC --> fB))
            (def c (newC --> fC))
            (def result 0.0)
            (if0 (a isa C)
                 (block (result = (a --> m (b c)))
                        (result = (result --> fC))
                 )
                 (if0 (a isa D)
                      (result = (a --> fD))
                      (result = a)))
            result)))
 (import A) (import B)
 (def x 3.7)
 (def y 8.2)
 (def z 41.9)
 (def newC (new C (x y z)))
 (def newD (new D (x y)))
 (newD --> m (newC z z))
)