((module A
    (class C (fA fB)
        (method cM ()
            (def x 1.0)
            (this --> m (x))
        )
        (method m (pA)
            (def x 1.0)
            (def y 2.0)
            (def c (new C (x y)))
            (c + pA)
        )
    )
 )
 (module B
    (import A)
    (class C (fA fB)
        (method cM ()
            (def x 3.0)
            (def y 26.9)
            (def c (new C (x y)))
            (c --> m (x))
        )
        (method m (pA) 0.0)
    )
 )
 (import B) (import A)
 (def x 1.0)
 (def y 2.0)
 (def c (new C (x y)))
 (c --> cM ())
)