(
    (module ma
              (class c (fa fb fc)
                       (method m (ma mb)
                                 (ma + mb)
                       )
              )
    )
    (module mb (import ma)
               (class b (fa fb fc)
                        (method m (ma mb mc)
                                  (def o (new c (ma mb mc)))
                                  o
                        )
               )
    )
    (import mb)
    (def a 1.0)
    (def b 2.0)
    (def c 3.0)
    (def o (new b (a b)))
    (def myo (o --> m (a b c)))
    (myo isa c)
)