(
    (module ma
              (class ca (fa fb fc)
                       (method m (ma mb)
                                 (ma + mb)
                       )
              )
    )
    (module mb (import ma)
               (class cb (fa fb fc)
                        (method m (ma mb mc)
                                  (def o (new ca (ma mb mc)))
                                  o
                        )
               )
    )
    (import ma) (import mb)
    (def a 1.0)
    (def b 2.0)
    (def c 3.0)
    (def o (new cb (a b c)))
    (def myo (o --> m (a b c)))
    (myo isa ca)
)