(
    (module ma
              (class c (fa fb fc)
                       (method m (ma mb)
                                 (ma + mb)
                       )
              )
    )
    (module mb (import ma)
               (class c (fa fb fc)
                        (method m (ma mb mc)
                                  (def o (new c (ma mb mc)))
                                  o
                        )
               )
    )
    (import ma) (import mb)
    (def a 1.0)
    (def b 2.0)
    (def cc 3.0)
    (def o (new c (a b cc)))
    (def myo (o --> m (a b cc)))
    (myo isa c)
)