(
    (module ma
              (class ca (fa fb fc)
                       (method m (ma mb)
                                 (ma + mb)
                       )
              )
    )
    (module mb (import ma)
               (class cb (fa fb fc)
                        (method m (ma mb mc)
                                  (def o (new ca (ma mb mc)))
                                  (this --> fa = o)
                                  0.0
                        )
               )
    )
    (import ma) (import mb)
    (def a 1.0)
    (def b 2.0)
    (def cc 3.0)
    (def o (new cb (a b cc)))
    (def myo (o --> m (a b cc)))
    (def aa (o --> fa))
    (aa isa ca)
)