(
  (class Warrior
    (hp atk log)
    (method init (startHP startATK startDEF)
      (def total (startHP + startATK))
      (self --> hp = startHP)
      (self --> atk = startATK)
      (self --> log = startDEF)
      total
    )
    (method attack (target)
      (def two 2.0)
      (def one 1.0)
      (if0 (target --> hp)
           (block
             (target --> hp = (target --> hp ))
             (self --> atk = (self --> atk ))
           )
           (block
             (target --> log = (target --> log))
           )
      )
      (self --> atk)
    )
  )
  (class Mage
    (mana power)
    (method cast (target)
      (def two 2.0)
      (def cost (mana / two))
      (while0 mana
        (block
          (mana = (mana / two))
          (target --> hp = (target --> hp))
        )
      )
      (mana == power)
    )
  )
  (def hero (new Warrior (a)))
  (def enemy (new Mage ()))
  (def five 5.0)
  (def two 2.0)
  (def one 1.0)
  (hero --> hp = (x + x))
  (hero --> atk = (hero --> atk))
  (if0 (hero --> log)
       (block
         (hero --> hp = (hero --> hp))
         (enemy --> power = (enemy --> power))
       )
       (block
         (enemy --> power = (enemy --> power))
       )
  )
  (while0 (hero --> atk)
    (block
      (hero --> atk = (hero --> atk))
      (enemy --> mana = (enemy --> mana))
    )
  )
  (hero isa Warrior)
)
