(
    (tmodule emptyclass
        (class EmptyClass ())
        (() ())
    )
    (module a 
        (class A (x)
            (method f ()
                (new A ())
            )
        )
    )
    (tmodule b 
        (timport a (((x Number)) ((f () Number))))
        (class B ()
            (method f ()
                (def var 1.5)
                (def a (new A (var)))
                (a --> x)
            )
        )
        (() ((f () Number)))
    )
    (tmodule c 
        (timport a (((x (() ()))) ((f () Number))))
        (import emptyclass)
        (class C ()
            (method f ()
                (def var (new EmptyClass ()))
                (def a (new A (var)))
                (def temp (a --> f ()))
                4.0
            )
        )
        (() ((f () Number)))
    )
    (module d 
        (import b)
        (import c)
        (class D ()
            (method f (n)
                (def b (new B ()))
                (def c (new C ()))
                (def var (b --> f ()))
                (def var (c --> f ()))
                n
            )
        )
    )
    (timport d (() ((f (Number) Number))))

    (def arg 6.7)
    (def d (new D ()))
    (d --> f (arg))
)