 ((tmodule M (class C (x)) (((x Number)) ()))
    (tmodule Mtwo (class Ctwo (x)) (((x Number)) ()))
    (import M) (import Mtwo)
    (def one 1.0)
    (def result 0.0)
    (def C (new C (one)))
    (def CC (new C (one)))
    (def Ctwo (new Ctwo (one)))
    (C = Ctwo)
    (if0 (C == CC) (result = 0.0)
                  (result = 1.0))
    (if0 (C == one) (result = 0.0)
                   (result = (result + one)))
    result)