(
  (tmodule Helper
    (class Helper () (method faveNum (x) x))
    (() ((faveNum (Number) Number)))
  )
  (module Insidious (import Helper)
    (class Insidious () 
      (method violation () 
        (def o (new Helper ()))
        (def x o)
        (def val (o --> faveNum(x)))
        (val isa Helper)
      )
    )
  )
  (timport Insidious (() ((violation () Number))))
  (def o (new Insidious ()))
  (o --> violation ())
)