((tmodule Animals
  (class Dog (x y)
    (method Reducespeed (x)
      (def y (this --> y))
      (x = 7.0)
      (x / y)))
  (((x Number) (y Number)) ((Reducespeed (Number) Number))))
  
(tmodule animal
  (class Dog (x y)
    (method Reducespeed (x)
      (def y (this --> y))
      (x = 5.0)
      (x / y)))
  (((x Number) (y Number)) ((Reducespeed (Number) Number))))
  
(import Animals)
(import animal)
(def x 5.0)
(def y 5.0)
(def Golden (new Dog (x y)))
(Golden --> x = x)
(Golden --> y = y)
(x = (Golden --> Reducespeed (x)))
x)