(
    (module a 
        (class A (x)
            (method f (y)
                (this --> x = this)
                (y --> y = this)
                this
            )
        )
    )
    (module b 
        (import a)
        (class B (y)
            (method f ()
                (def y (this --> y))
                (def temp 0.0)
                (this = (new A (this)))
                (temp = (this --> f (y)))
                (temp = (this --> x))
                (temp = (this --> x))
                (temp = (this --> x))
                (this --> x = 4.2)
                y
            )
        )
    )
    (import b)
    (def var 0.0)
    (var = (new B (var)))
    (var --> y = var)
    (var = (var --> f ()))
    (var = (var --> y))
    (var --> x)
)