(
    (tmodule stop
        (class Stop () 
            (method f (x y)
                y
            )
        )
        (() ((f (Number Number) Number)))
    )
    (module a 
        (import stop)
        (class A ()
            (method f (x y)
                (def negOne -1.0)
                (if0 x 
                    (this = (new Stop ()))
                    (this = this)
                )
                (y = (y + x))
                (x = (x + negOne))
                (this --> f (x y))
            )
            (method g (x)
                (this --> f (x x))
            )
        )
    )
    (timport a (() ((g (Number) Number))))
    (def a (new A ()))
    (def x 5.0)
    (a --> g (x))
)