((tmodule
  ShapeA
  (class ShapeA (x y)
    (method area (factor)
      (def a (this --> x))
      (def b (this --> y))
      (def c (a + b))
      (c + factor)))
  (((x Number) (y Number))
   ((area (Number) Number))))
 (tmodule
  ShapeB
  (class ShapeB (x y)
    (method area (factor scale)
      (def a (this --> x))
      (def b (this --> y))
      (def c (a + b))
      (c + scale)))
  (((x Number) (y Number))
   ((area (Number Number) Number))))
 (import ShapeA)
 (import ShapeB)
 (def x 3.0)
 (def y 4.0)
 (def f 1.0)
 (def sA (new ShapeA (x y)))
 (def sB (new ShapeB (x y)))
 (sA == sB))