( (module C
   (class Z
   (f)
   (method
    eq
    (other)
    (def old (this --> f))
    (def myf old)
    (def urf (other --> f))
    (def res 1.0)
    (if0 (old isa Z) (this --> f = 42.0) (this --> f = (old + res)))
    (urf = (other --> f))
    (myf = (this --> f))
    (res = (urf == myf))
    (this --> f = old)
    res))
)
(import C)
 (def one 1.0)
 (def c (new Z (one)))
 (def d c)
 (def e (new Z (c)))
 (one = (c --> eq (d)))
 (d = (c --> eq (e)))
 (one + d))