((def sum 0.0)
 (def i 5.0) 
 (def continue 0.0)
  (def zero 0.0) 
  (def one 1.0) 
  (def negOne -1.0) 
  (while0 continue
   (block (def tempSum (sum + i))
    (def tempI (i + negOne)) 
    (sum = tempSum) 
    (i = tempI) 
    (if0 (i == zero) 
    (continue = one) (continue = zero)))) sum)