(
(def a 4.0)
(def b 5.0) 
(def product 0.0) 
(def counter b) 
(def continueLoop 0.0)
 (def zero 0.0) 
 (def one 1.0) 
 (def negOne -1.0) 
 (def twenty 20.0) 
 (def four 4.0) 
 (def finalResult 0.0)
  (def successCode 100.0)
  (def failureCodeA -100.0) 
  (def failureCodeProd -200.0) 
  (while0 continueLoop 
  (block (def tempProd (product + a))
   (def tempCount (counter + negOne)) 
   (def a -99.0) 
   (def tempLocalA (a + one)) 
   (product = tempProd) 
   (counter = tempCount) 
   (a = tempLocalA) 
   (if0 (counter == zero)
    (continueLoop = one) 
    (continueLoop = zero)))) 
    (if0 (product == twenty) 
    (if0 (a == four) 
    (finalResult = successCode)
     (finalResult = failureCodeA)) 
     (finalResult = failureCodeProd)) 
     finalResult)