((module Math (class Vector (dx dy)))
 (module Geometry (import Math)
   (class Point (x y)
     (method makeVector ()
       (def vx (this --> x))
       (def vy (this --> y))
       (def result (new Vector (vx vy)))
       result)))
 (import Geometry)
 (def a 3.0)
 (def b 4.0)
 (def p (new Point (a b)))
 (p --> makeVector ()))