((module Base (class Node (value)))
 (module List (import Base)
   (class LinkedList (head)
     (method getHead ()
       (this --> head))))
 (import List)
 (import Base)
 (def val 42.0)
 (def node (new Node (val)))
 (def list (new LinkedList (node)))
 (def retrieved (list --> getHead ()))
 (retrieved --> value))