((module Utils (class Calculator (base)
     (method add (a b)
       (def result (a + b))
       result)))
 (import Utils)
 (def baseVal 0.0)
 (def calc (new Calculator (baseVal)))
 (def arg 5.0)
 (calc --> add (arg)))