((module Math (class Divider ()
     (method divide (numerator denominator)
       (def result (numerator / denominator))
       result)))
 (import Math)
 (def d (new Divider ()))
 (def num 10.0)
 (def denom 0.0)
 (d --> divide (num denom)))