((module Math
  (class Calculate ()
    (method divide (x y)
            (y / x))
    (method add (x y)
            (x + y))
    (method equal (x y)
            (x == y))
    ))
 (import Math)
 (def three 3.0)
 (def zero 0.0)
 (def c (new Calculate ()))
 (if0 (c --> equal (three zero))
      (block
       (def eight 8.0)
       (def negativeEight 8.0)
       (eight = (c --> add (eight negativeEight))))
      (zero = (c --> divide (three three))))
 (new Calculate ()))