((tmodule
  Point
  (class Point (x y)
    (method delta (x)
      (def y (this --> y))
      (def tmp (y + x))
      (x = 1.0)
      (tmp + y)))
  (((x Number) (y Number))
   ((delta (Number) Number)))
 )
 (module
  PointTemp
  (class Point (x y)
    (method delta (x)
      (def y (this --> y))
      (def z (x + y))
      (x = 1.0)
      (z + y)))
 )
 (tmodule
  PointTwo
  (timport PointTemp (( (y Number))
                      ((delta (Number) Number)))
                      )
  (timport PointTemp (( (y Number))
                      ((delta (Number) Number)))
                      )
  (class Point
    (x y z)
    (method delta ()
      (def x (this --> x))
      (def y (this --> y))
      (def z (this --> z))
      (z = (x + y))
      (z + y)))
  (((x Number) (y Number) (z Number))
   ((delta () Number)))
 )

 (import Point)
 (timport PointTemp (((x Number) (y Number))
                      ((delta (Number) Number))))
  (timport PointTemp (((x Number) (y Number))
                      ((delta (Number) Number))))
 (def x 1.0)
 (def point (new Point (x x)))
 (point --> x = x)
 (x = (point --> delta (x)))
 x)
