(
    (class A (fa fb fc)
             (method sum ()
                (def sum 0.0)
                (def fa (this --> fa))
                (def fb (this --> fb))
                (def fc (this --> fc))
                (sum = (fa + fb))
                (sum = (sum + fc))
                sum)
    )
    (class B (fa fb fc)
             (method sum (this)
                (def sum 0.0)
                (def fa (this --> fa))
                (def fb (this --> fb))
                (def fc (this --> fc))
                (sum = (fa + fb))
                (sum = (sum + fc))
                sum)
    )
    (def one 1.0)
    (def two 2.0)
    (def three 3.0)
    (def cA (new A (one two three)))
    (def cB (new B (one one one)))
    (def result 0.0)
    (def same 0.0)
    (result = (cA --> sum ()))
    (cB = (cB --> sum (one)))
    (result = (result + cB))
    (cB = (new A (one two three)))
    (same = (cA == cB))
    (result = (result + same))
    (cA --> fa = three)
    (cB = (cA --> fa))
    (result = (result + cB))
    (cA --> fa = (new B (one two three)))
    (cB = (cA --> fa))
    (if0 (cB isa B)
         (block (result = (result + one)))
         (block (result = (result + three))))
    (while0 (cB isa B)
            (block (cB = 1.0)
                   (result = (result + cB))))
    result
)
