(
    (class Add (x y)
               (method calculate ()
                                 (def xVal (this --> x))
                                 (def yVal (this --> y))
                                 (xVal + yVal)
               )
    )
    (class Divide (x y)
               (method calculate ()
                                 (def xVal (this --> x))
                                 (def yVal (this --> y))
                                 (xVal / yVal)
               )
    )
    (class XYCalculator (Add Divide)
                        (method init (x y)
                                     (this --> Add = (new Add (x y)))
                                     (this --> Divide = (new Divide (x y)))
                                     0.0
                        )
                        (method Add ()
                                    (def Add (this --> Add))
                                    (Add --> calculate ())
                        )
                        (method Divide ()
                                       (def Divide (this --> Divide))
                                       (Divide --> calculate ())
                        )
    )
    (def result 0.0)
    (def tmp 0.0)
    (def one 1.0)
    (def four 4.0)
    (def a 0.0)
    (a = (new XYCalculator (a a)))
    (tmp = (a --> init (one four)))
    (result = (a --> Add ()))
    (tmp = (a --> Divide ()))
    (result = (result + tmp))
    result
)