((class A (x))
 (class B (y))
 (def one 1.0)
 (def z 0.0)
 (def bOne (new B (one)))
 (def bTwo (new B (one)))
 (def bbOne (new B (bOne)))
 (def bbTwo (new B (bTwo)))
 (def bbbOne (new B (bbOne)))
 (def bbbTwo (new B (bbTwo)))
 (def bbbbOne (new B (bbbOne)))
 (def bbbbTwo (new B (bbbTwo)))
 (def aOne (new A (bbbbOne)))
 (def aTwo (new A (bbbbTwo)))
 (aOne == aTwo))