(
    (class A (fa fb fc)
             (method sum ()
                (def sum 0.0)
                (def fa (this --> fa))
                (def fb (this --> fb))
                (def fc (this --> fc))
                (sum = (fa + fb))
                (sum = (sum + fc))
                sum)
    )
    (class B (fa fb fc)
             (method sum (this)
                (def sum 0.0)
                (def fa (this --> fa))
                (def fb (this --> fb))
                (def fc (this --> fc))
                (sum = (fa + fb))
                (sum = (sum + fc))
                sum)
    )
    (def one 1.0)
    (def two 2.0)
    (def three 3.0)
    (def four 4.0)
    (def cA (new A (one two three)))
    (def cB (new B (one one one)))
    (def result 0.0)
    (cA --> f = cB)
    (result = (cA --> fa))
    result
)
