(
    (class Vec (x y z)
        (method shiftByAmounts (x y z)
            (def curx (this --> x))
            (def cury (this --> y))
            (def curz (this --> z))
            (this --> x = (curx + x))
            (this --> y = (cury + y))
            (this --> z = (curz + z))
            this
        )
        (method shiftByVec (vec)
            (def shiftx (vec --> x))
            (def shifty (vec --> y))
            (def shiftz (vec --> z))
            (this --> shiftByAmounts (shiftx shifty shiftz))
        )
        (method scaleByAmount (s)
            (if0 s 
                (block
                    (this --> x = 0.0)
                    (this --> y = 0.0)
                    (this --> z = 0.0)
                )
                (block 
                    (def one 1.0)
                    (def inverted (one / s))
                    (def curx (this --> x))
                    (def cury (this --> y))
                    (def curz (this --> z))
                    (this --> x = (curx / inverted))
                    (this --> y = (cury / inverted))
                    (this --> z = (curz / inverted))
                )
            )
            this
        )
        (method flip ()
            (def negOne -1.0)
            (this --> scaleByAmount (negOne))
        )
        (method zero ()
            (def zero 0.0)
            (this --> scaleByAmount (zero))
        )
    )
    (def x 1.5)
    (def y 2.0)
    (def z 2.5)
    (def u (new Vec (x y z)))
    (def v (new Vec (x x x)))
    (def temp (u --> shiftByVec (v)))
    (def temp (u --> flip ()))
    (u --> y)
)