(
    (class A (x)) 
    (class B (x)) 
    (def temp 0.0) 
    (def templol 0.0) 
    (def a (new A (temp))) 
    (def b (new B (temp))) 
    (def otherA (new A (temp))) 
    (def otherB (new B (temp))) 
    (def result 0.0) 
    (a --> x = b) 
    (b --> x = a) 
    (otherA --> x = otherB) 
    (templol = (new B (otherA))) 
    (temp = (new A (templol))) 
    (otherB --> x = temp) 
    (if0 (a == otherA) 
        (result = 0.0) 
        (result = 1.0)
    ) 
    result
)