((tmodule Vehicle
    (class Car (year tankAmount)
      (method getYear ()
        (this --> year)))
    (((Year Number)
      (tankAmount Number))
     ((getYear () Number))))
  (tmodule SeaVehicle
    (timport Vehicle (((year Number)
      (tankAmount Number))
     ((getYear () Number))))       
    (class boat (length tankAmount)
      (method getLength ()
        (this --> length)))
    (((length Number)
      (tankAmount Number))
     ((getLength () Number))))
  0.0)