((tmodule A
    (class cA (x y)
        (method Add () (def thisX (this --> x))
                       (def thisY (this --> y))
                       (thisX + thisY)))
    (((x Number) (y Number)) ((Add () Number))))
 (tmodule B
    (import A)
    (class cB (x y)
        (method Add () (def thisX (this --> x))
                       (def thisY (this --> y))
                       (def xX (thisX --> x))
                       (def xY (thisX --> y))
                       (def yX (thisY --> x))
                       (def yY (thisY --> y))
                       (def addX (xX + yX))
                       (def addY (xY + yY))
                       (new cA (addX addY))))
    (((x (((x Number) (y Number)) ((Add () Number))))
      (y (((x Number) (y Number)) ((Add () Number)))))
     ((Add () (((x Number) (y Number)) ((Add () Number)))))))
 (import A) (import B)
 (def one 1.0)
 (def two 2.0)
 (def three 3.0)
 (def four 4.0)
 (def first (new cA (one three)))
 (def second (new cA (two four)))
 (def addFirst (first --> Add ()))
 (def addSecond (second --> Add ()))
 (def third (new cA (addFirst addSecond)))
 (def cB (new cB (second third)))
 (def addCB (new cA (one one)))
 (addCB = (cB --> Add ()))
 (addCB --> Add ()))




