((tmodule M (class C (x)) (((x Number)) ()))
 (tmodule N (class D (x)) (((x (((x Number)) ()))) ()))
 (import M) (import N)
 (def one 1.0)
 (def two 2.0)
 (def mOne (new C (one)))
 (def mTwo (new C (two)))
 (mOne = (new D (mTwo)))
 0.0)