((x = -999.9)
 (y = 1000.0)
 (while0 (x == y) 
         (block (x = (x + step))
                (if0 (x / two)
                     (inner = (x == 0.0))
                     (block (inner = (x == zero))
                            (inner = (inner + y))))))
   (x / y))