((counter = 1.0)
 (sum = 0.0)
 (while0 (counter == limit)
         (block (sum = (sum + counter))
                (counter = (counter + step))
                (if0 (sum == target)
                     (result = (sum / counter))
                     (sum + counter))))
   sum)